# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae2d61498a50611ac7c18d8ea5e05ec7ceff97a816cdcd76ad3afbc7f9109bad1e9cdb96a4830dca2000ffb3a635611177b99655d4699dcbae8a01db8037708

test:
  secret_key_base: fe9b04b963fe7e438911dbc2d4ad0fc49628eedc7e0d5aefdf6f06c2e7bd18f414d2cfcb7ca9b53ab388679ad75b8bb71628ac8e2daf21e8073e4e63337c0145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
